### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by ghost** [pevdh/telegram-bots-java-api#2]
I'm having the following exception after leaving the bot for a while:

```
java.util.concurrent.ExecutionException: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was -1001035840229 at line 2 column 145 path $.result[0].message.chat.id
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at co.vandenham.telegram.botapi.requests.ApiRequestExecutor$AsyncApiResponse.getResult(ApiRequestExecutor.java:80)
    at co.vandenham.telegram.botapi.TelegramBot$UpdatePoller.poll(TelegramBot.java:521)
    at co.vandenham.telegram.botapi.TelegramBot$UpdatePoller.run(TelegramBot.java:509)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was -1001035840229 at line 2 column 145 path $.result[0].message.chat.id
    at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:249)
    at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:239)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:116)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:116)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:116)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:116)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
    at com.google.gson.Gson.fromJson(Gson.java:879)
    at com.google.gson.Gson.fromJson(Gson.java:844)
    at com.google.gson.Gson.fromJson(Gson.java:793)
    at co.vandenham.telegram.botapi.requests.ApiRequestExecutor.deserialize(ApiRequestExecutor.java:29)
    at co.vandenham.telegram.botapi.requests.ApiRequestExecutor.makeRequest(ApiRequestExecutor.java:37)
    at co.vandenham.telegram.botapi.requests.ApiRequestExecutor$AsyncApiRequestExecutor$1.call(ApiRequestExecutor.java:97)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    ... 1 more
Caused by: java.lang.NumberFormatException: Expected an int but was -1001035840229 at line 2 column 145 path $.result[0].message.chat.id
    at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1172)
    at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:247)
    ... 22 more
Exception in thread "Thread-1" java.lang.NullPointerException
    at co.vandenham.telegram.botapi.TelegramBot$UpdatePoller.poll(TelegramBot.java:522)
    at co.vandenham.telegram.botapi.TelegramBot$UpdatePoller.run(TelegramBot.java:509)
    at java.lang.Thread.run(Thread.java:745)
```

Using latest commit of TelegramBots4Java and GSON 2.6.2.

**Comment by pevdh** [comment]
Is this still an issue?
I haven't visited this project for a while. I noticed that Telegram changed their API quite a lot. It could be due to a change in the types Telegram uses (`int` to `long`?). I don't know.
I do not really have the time at this moment to improve this project, so any help is appreciated!
